layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  linkedin: marlesson-santana-25019358
  medium: '@marlessonsantana'
  twitter: marlesson

  #behance: your_username
  #dribbble: your_username
  #facebook: your_username
  #stackoverflow: your_user_id
  #youtube: your_username

topics:
  - name: Machine Learning
    image_url: http://blog.yhat.com/static/img/NN.png

  - name: Data Science
    image_url: https://image.freepik.com/vetores-gratis/ciencia-de-dados-ilustracao-com-pessoa-e-icones_1124-392.jpg

  - name: Python
    image_url: https://www.python.org/static/opengraph-icon-200x200.png

  - name: Google Cloud Platform
    web_url: https://cloud.google.com/
    image_url: https://www.sumologic.com/wp-content/uploads/gcp-logo-1.png

  - name: Hadoop
    web_url: https://hadoop.apache.org/
    image_url: https://i2.wp.com/www.cienciaedados.com/wp-content/uploads/2015/12/Hadoop.png?resize=297%2C288

  - name: Spark
    web_url: https://spark.apache.org/
    image_url: https://cdn-images-1.medium.com/max/1200/1*Pa7PO1v7bANI7C-eHMS_PQ.png

  - name: TensorFlow
    web_url: https://www.tensorflow.org/
    image_url: http://www.lapix.ufsc.br/wp-content/uploads/2018/04/q8sc1KuZ_400x400.jpg

  - name: Scikit-learn
    web_url: https://scikit-learn.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Scikit_learn_logo_small.svg/1200px-Scikit_learn_logo_small.svg.png

